[2020-12-25 16:46:54,602] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.docker_op_tester 2020-12-25T08:46:50.929668+00:00 [queued]>
[2020-12-25 16:46:54,606] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.docker_op_tester 2020-12-25T08:46:50.929668+00:00 [queued]>
[2020-12-25 16:46:54,606] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2020-12-25 16:46:54,606] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2020-12-25 16:46:54,606] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2020-12-25 16:46:54,614] {taskinstance.py:1038} INFO - Executing <Task(DockerOperator): docker_op_tester> on 2020-12-25T08:46:50.929668+00:00
[2020-12-25 16:46:54,616] {standard_task_runner.py:51} INFO - Started process 26840 to run task
[2020-12-25 16:46:54,618] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'foodpanda', 'docker_op_tester', '2020-12-25T08:46:50.929668+00:00', '--job-id', '48', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ssh_practice.py', '--cfg-path', '/tmp/tmpalg8domd']
[2020-12-25 16:46:54,618] {standard_task_runner.py:76} INFO - Job 48: Subtask docker_op_tester
[2020-12-25 16:46:54,634] {logging_mixin.py:103} INFO - Running <TaskInstance: foodpanda.docker_op_tester 2020-12-25T08:46:50.929668+00:00 [running]> on host dataiku
[2020-12-25 16:46:54,648] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=arthur.sl.lin
AIRFLOW_CTX_DAG_ID=foodpanda
AIRFLOW_CTX_TASK_ID=docker_op_tester
AIRFLOW_CTX_EXECUTION_DATE=2020-12-25T08:46:50.929668+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2020-12-25T08:46:50.929668+00:00
[2020-12-25 16:46:54,656] {docker.py:287} INFO - Pulling docker image centos:latest
[2020-12-25 16:46:57,320] {docker.py:301} INFO - latest: Pulling from library/centos
[2020-12-25 16:46:58,189] {docker.py:301} INFO - 7a0437f04f83: Pulling fs layer
[2020-12-25 16:46:59,187] {docker.py:301} INFO - 7a0437f04f83: Downloading
[2020-12-25 16:47:07,629] {docker.py:301} INFO - 7a0437f04f83: Download complete
[2020-12-25 16:47:07,719] {docker.py:301} INFO - 7a0437f04f83: Extracting
[2020-12-25 16:47:09,629] {docker.py:301} INFO - 7a0437f04f83: Pull complete
[2020-12-25 16:47:09,636] {docker.py:296} INFO - Digest: sha256:5528e8b1b1719d34604c87e11dcd1c0a20bedf46e83b5632cdeac91b8c04efc1
[2020-12-25 16:47:09,642] {docker.py:296} INFO - Status: Downloaded newer image for centos:latest
[2020-12-25 16:47:09,642] {docker.py:224} INFO - Starting docker container from image centos:latest
[2020-12-25 16:47:40,179] {xcom.py:238} ERROR - Could not serialize the XCom value into JSON. If you are using pickles instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2020-12-25 16:47:40,179] {taskinstance.py:1396} ERROR - Object of type 'bytes' is not JSON serializable
Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1303, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1833, in xcom_push
    session=session,
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/utils/session.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/xcom.py", line 88, in set
    value = XCom.serialize_value(value)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/xcom.py", line 235, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
[2020-12-25 16:47:40,180] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=foodpanda, task_id=docker_op_tester, execution_date=20201225T084650, start_date=20201225T084654, end_date=20201225T084740
[2020-12-25 16:47:40,226] {local_task_job.py:118} INFO - Task exited with return code 1
