[2020-12-25 16:02:12,660] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.also_run_this 2020-12-25T08:02:08.203118+00:00 [queued]>
[2020-12-25 16:02:12,663] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.also_run_this 2020-12-25T08:02:08.203118+00:00 [queued]>
[2020-12-25 16:02:12,663] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2020-12-25 16:02:12,663] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2020-12-25 16:02:12,663] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2020-12-25 16:02:12,673] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): also_run_this> on 2020-12-25T08:02:08.203118+00:00
[2020-12-25 16:02:12,673] {base_task_runner.py:121} INFO - Running on host: dataiku
[2020-12-25 16:02:12,673] {base_task_runner.py:122} INFO - Running: ['airflow', 'tasks', 'run', 'foodpanda', 'also_run_this', '2020-12-25T08:02:08.203118+00:00', '--job-id', '72', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ssh_practice.py', '--cfg-path', '/tmp/tmp009jpos5']
[2020-12-25 16:02:13,236] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this [2020-12-25 16:02:13,236] {dagbag.py:440} INFO - Filling up the DagBag from /home/ub/airflow/dags/ssh_practice.py
[2020-12-25 16:02:13,327] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this Running <TaskInstance: foodpanda.also_run_this 2020-12-25T08:02:08.203118+00:00 [running]> on host dataiku
[2020-12-25 16:02:13,341] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=arthur.sl.lin
AIRFLOW_CTX_DAG_ID=foodpanda
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2020-12-25T08:02:08.203118+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2020-12-25T08:02:08.203118+00:00
[2020-12-25 16:02:13,342] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2020-12-25 16:02:13,342] {bash.py:158} INFO - Running command: docker run -d hello-world
[2020-12-25 16:02:13,345] {bash.py:169} INFO - Output:
[2020-12-25 16:02:13,370] {bash.py:173} INFO - docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
[2020-12-25 16:02:13,370] {bash.py:173} INFO - See 'docker run --help'.
[2020-12-25 16:02:13,372] {bash.py:177} INFO - Command exited with return code 126
[2020-12-25 16:02:13,375] {taskinstance.py:1396} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2020-12-25 16:02:13,375] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=foodpanda, task_id=also_run_this, execution_date=20201225T080208, start_date=20201225T080212, end_date=20201225T080213
[2020-12-25 16:02:13,386] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this Traceback (most recent call last):
[2020-12-25 16:02:13,386] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this   File "/home/ub/airflow/env/bin/airflow", line 8, in <module>
[2020-12-25 16:02:13,386] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this     sys.exit(main())
[2020-12-25 16:02:13,386] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this   File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/__main__.py", line 40, in main
[2020-12-25 16:02:13,386] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this     args.func(args)
[2020-12-25 16:02:13,386] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this   File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
[2020-12-25 16:02:13,387] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this     return func(*args, **kwargs)
[2020-12-25 16:02:13,387] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this   File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/utils/cli.py", line 89, in wrapper
[2020-12-25 16:02:13,387] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this     return f(*args, **kwargs)
[2020-12-25 16:02:13,387] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this   File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 234, in task_run
[2020-12-25 16:02:13,387] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this     _run_task_by_selected_method(args, dag, ti)
[2020-12-25 16:02:13,387] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this   File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 66, in _run_task_by_selected_method
[2020-12-25 16:02:13,387] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this     _run_raw_task(args, ti)
[2020-12-25 16:02:13,387] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this   File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 151, in _run_raw_task
[2020-12-25 16:02:13,387] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this     pool=args.pool,
[2020-12-25 16:02:13,387] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this   File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/utils/session.py", line 65, in wrapper
[2020-12-25 16:02:13,387] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this     return func(*args, session=session, **kwargs)
[2020-12-25 16:02:13,388] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this   File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
[2020-12-25 16:02:13,388] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this     self._prepare_and_execute_task_with_callbacks(context, task)
[2020-12-25 16:02:13,388] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this   File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
[2020-12-25 16:02:13,388] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this     result = self._execute_task(context, task_copy)
[2020-12-25 16:02:13,388] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this   File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
[2020-12-25 16:02:13,388] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this     result = task_copy.execute(context=context)
[2020-12-25 16:02:13,388] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this   File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
[2020-12-25 16:02:13,389] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this     raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
[2020-12-25 16:02:13,389] {base_task_runner.py:106} INFO - Job 72: Subtask also_run_this airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2020-12-25 16:02:13,531] {local_task_job.py:118} INFO - Task exited with return code 1
